name: Deploy K8s Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to WSL2 SSH
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: pbarysiuk.onedumb.com
          port: 8228
          user: pbarysiuk
          key: ${{ secrets.WSL2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/pbarysiuk/personal/learn/k8s/local_k8s &&
            ls -la &&
            terraform init &&
            terraform apply --auto-approve &&
