name: Deploy K8s Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to WSL2 SSH
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: pbarysiuk.onedumb.com
          port: 8228
          user: pbarysiuk
          key: ${{ secrets.WSL2_SSH_PRIVATE_KEY }}

      - name: Terraform init and apply
        run: |
          terraform init
          terraform apply --auto-approve
